version: '2'

services:

  datafeed:
    image: datafeed
    build:
      context: .
      dockerfile: Dockerfile-datafeed
    links:
      - datastore
    environment:
      - WS_CONNECTION
      - IMG_PROXY_PREFIX

  datastore:
    image: datastore
    build:
      context: .
      dockerfile: Dockerfile-datastore
    ports:
      - "3301:3301"
    volumes:
      - ./data:/var/lib/tarantool
      - ./:/home/src
